apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-service-nodeport
  labels:
    app: cat-service-nodeport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cat-service-nodeport
  template:
    metadata:
      labels:
        app: cat-service-nodeport
    spec:
      containers:
      - name: cat-website
        image: jfarag242/k8s-sample-app-cats:0.0.2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cat-service-nodeport
spec:
  selector:
    app: cat-service-nodeport
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---

