apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-service-loadbalancer
  labels:
    app: cat-service-loadbalancer

spec:
  replicas: 3
  selector:
    matchLabels:
      app: cat-service-loadbalancer
  
  template:
    metadata:
      labels:
        app: cat-service-loadbalancer
    
    spec:
      containers:
      - name: cat-website
        image: jfarag242/k8s-sample-app-cats:0.0.3
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cat-service-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip" 
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  selector:
    app: cat-service-loadbalancer



  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---

