apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-service-loadbalancer
  labels:
    app: dog-service-loadbalancer

spec:
  replicas: 3
  selector:
    matchLabels:
      app: dog-service-loadbalancer
  
  template:
    metadata:
      labels:
        app: dog-service-loadbalancer
    
    spec:
      containers:
      - name: dog-website
        image: jfarag242/k8s-sample-app-dogs:0.0.3
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dog-service-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip" #target = Pod IPs
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"

spec:
  selector:
    app: dog-service-loadbalancer

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---

