apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-service-headless
  labels:
    app: cat-service-headless
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cat-service-headless
  template:
    metadata:
      labels:
        app: cat-service-headless
    spec:
      containers:
      - name: cat-website
        image: jfarag242/k8s-sample-app-cats:0.0.2
        ports:
        - containerPort: 80
        # added health check 
        # container will not receive traffic until ready
        readinessProbe:
          tcpSocket:
            port: 80 # open tcp socket on port 80
          initialDelaySeconds: 15 # first probe 15 seconds after container start
          periodSeconds: 10 # check every 10 seconds
        # if fail container restarts
        livenessProbe:
          tcpSocket:
            port: 80 
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: cat-service-headless
spec:
  selector:
    app: cat-service-headless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: "None"
---





apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: registry.k8s.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
